name: GitHubFlask
on: push

jobs:
  my-job:
    name: CI Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3 
    - name: CItest
      run: |
        python -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Run server
      run: |    
        python3 server.py > log.txt 2>&1 &
        python -m pip install --upgrade pip setuptools wheel
        pip3 install pytest Flask-Testing